export type UserType = "public" | "private";

export interface User {
  rank: number;
  name: string;
  login: string;
  avatarUrl: string;
  contributions: number;
  company: string;
  organizations: string;
}

/**
 * The shape of `src/data/committers.json`, regenerated by
 * `pnpm data:build` (see `scripts/build-data.ts`).
 */
export interface CommittersSnapshot {
  /** Country slug on committers.top, e.g. "uzbekistan". */
  country: string;
  /** When the upstream ranking itself was computed, as reported by the source. */
  dataAsOf: string;
  /** ISO timestamp of when this snapshot file was written. */
  fetchedAt: string;
  /** Public-contributions ranking. */
  public: User[];
  /** Ranking that also counts private contributions. */
  private: User[];
}
