export type UserType = "public" | "private";

export interface User {
  rank: number;
  name: string;
  login: string;
  avatarUrl: string;
  contributions: number;
  company: string;
  organizations: string;
}

/**
 * The shape of `src/data/committers/<slug>.json`, regenerated by
 * `pnpm data:build` (see `scripts/build-data.ts`).
 */
export interface CommittersSnapshot {
  /** Country slug on committers.top, e.g. "uzbekistan". */
  country: string;
  /** Display name as published by the source, e.g. "Uzbekistan". */
  title: string;
  /** When the upstream ranking itself was computed, as reported by the source. */
  dataAsOf: string;
  /** ISO timestamp of when this snapshot file was written. */
  fetchedAt: string;
  /** Public-contributions ranking. */
  public: User[];
  /** Ranking that also counts private contributions. */
  private: User[];
}

/** One row of `src/data/stats.json` — a country's headline numbers. */
export interface CountryStatsEntry {
  slug: string;
  title: string;
  flag: string;
  /** GitHub users the source found in the region, not just the ranked ones. */
  totalUsers: number;
  /** Followers needed to appear on the ranking at all. */
  minFollowers: number;
  /** Summed contributions of the ranked users — the source caps the list at 256. */
  rankedContributions: number;
  rankedUsers: number;
  topUser: { login: string; name: string; avatarUrl: string; contributions: number } | null;
}

/** `src/data/stats.json`. */
export interface GlobalStats {
  /** ISO timestamp of when the stats were collected. */
  generatedAt: string;
  countries: CountryStatsEntry[];
}

/** One country outline in `src/data/world-map.json`. */
export interface MapShape {
  /** committers.top slug, or null when the country has no leaderboard. */
  slug: string | null;
  name: string;
  /** SVG path data, already projected into the viewBox below. */
  d: string;
}

/** `src/data/world-map.json`. */
export interface WorldMap {
  width: number;
  height: number;
  shapes: MapShape[];
}

/** One entry of `src/data/countries.json`. */
export interface Country {
  /** committers.top slug, e.g. "bosnia_and_herzegovina". */
  slug: string;
  /** Display name, e.g. "Bosnia and Herzegovina". */
  title: string;
  /** Regional indicator emoji, or an empty string when no ISO code was resolved. */
  flag: string;
}
